name: reflex_war
description: A reflex battle game for 1-4 players.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.4.9
  equatable: ^2.0.5
  google_fonts: ^6.1.0
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.5.4
  audioplayers: ^6.5.1
  vibration: ^3.1.5
  # google_mobile_ads: ^7.0.0 (Disabled for Build Fix)
  url_launcher: ^6.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.10

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_icon.png"

flutter_native_splash:
  color: "#000000"
  image: "assets/icon/app_icon.png"
  android: true
  ios: true

flutter:
  uses-material-design: true
  assets:
    - assets/sounds/
